/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProceduresIndexRouteImport } from './routes/procedures.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProceduresCodeRouteImport } from './routes/procedures.$code'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as CSessionIdRouteImport } from './routes/c.$sessionId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminProceduresRouteImport } from './routes/admin.procedures'
import { Route as AdminSourcesSourceIdRouteImport } from './routes/admin.sources_.$sourceId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresIndexRoute = ProceduresIndexRouteImport.update({
  id: '/procedures/',
  path: '/procedures/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProceduresCodeRoute = ProceduresCodeRouteImport.update({
  id: '/procedures/$code',
  path: '/procedures/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CSessionIdRoute = CSessionIdRouteImport.update({
  id: '/c/$sessionId',
  path: '/c/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProceduresRoute = AdminProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesSourceIdRoute = AdminSourcesSourceIdRouteImport.update({
  id: '/sources_/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/news/$id': typeof NewsIdRoute
  '/procedures/$code': typeof ProceduresCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
  '/admin/sources/$sourceId': typeof AdminSourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/news/$id': typeof NewsIdRoute
  '/procedures/$code': typeof ProceduresCodeRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
  '/procedures': typeof ProceduresIndexRoute
  '/admin/sources/$sourceId': typeof AdminSourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/news/$id': typeof NewsIdRoute
  '/procedures/$code': typeof ProceduresCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
  '/admin/sources_/$sourceId': typeof AdminSourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/procedures'
    | '/admin/sources'
    | '/admin/users'
    | '/c/$sessionId'
    | '/news/$id'
    | '/procedures/$code'
    | '/admin/'
    | '/news/'
    | '/procedures/'
    | '/admin/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/procedures'
    | '/admin/sources'
    | '/admin/users'
    | '/c/$sessionId'
    | '/news/$id'
    | '/procedures/$code'
    | '/admin'
    | '/news'
    | '/procedures'
    | '/admin/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/admin/procedures'
    | '/admin/sources'
    | '/admin/users'
    | '/c/$sessionId'
    | '/news/$id'
    | '/procedures/$code'
    | '/admin/'
    | '/news/'
    | '/procedures/'
    | '/admin/sources_/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CSessionIdRoute: typeof CSessionIdRoute
  NewsIdRoute: typeof NewsIdRoute
  ProceduresCodeRoute: typeof ProceduresCodeRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProceduresIndexRoute: typeof ProceduresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/': {
      id: '/procedures/'
      path: '/procedures'
      fullPath: '/procedures/'
      preLoaderRoute: typeof ProceduresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/procedures/$code': {
      id: '/procedures/$code'
      path: '/procedures/$code'
      fullPath: '/procedures/$code'
      preLoaderRoute: typeof ProceduresCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sessionId': {
      id: '/c/$sessionId'
      path: '/c/$sessionId'
      fullPath: '/c/$sessionId'
      preLoaderRoute: typeof CSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procedures': {
      id: '/admin/procedures'
      path: '/procedures'
      fullPath: '/admin/procedures'
      preLoaderRoute: typeof AdminProceduresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources_/$sourceId': {
      id: '/admin/sources_/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/admin/sources/$sourceId'
      preLoaderRoute: typeof AdminSourcesSourceIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProceduresRoute: typeof AdminProceduresRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSourcesSourceIdRoute: typeof AdminSourcesSourceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProceduresRoute: AdminProceduresRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSourcesSourceIdRoute: AdminSourcesSourceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CSessionIdRoute: CSessionIdRoute,
  NewsIdRoute: NewsIdRoute,
  ProceduresCodeRoute: ProceduresCodeRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProceduresIndexRoute: ProceduresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
